spring:
        
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: tester2
    # password 주의 !
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
#    hibernate에 실행하는 쿼리가 로그 레벨로 출력

server:
  port: 9090