 DROP TRIGGER TRG_TB_BOARD;
 DROP TABLE TB_BOARD;
 DROP SEQUENCE SEQ_TB_BOARD;

 -- 시퀀스 생성
 CREATE SEQUENCE SEQ_TB_BOARD
     START WITH 1
     INCREMENT BY 1
     NOMAXVALUE
     NOCYCLE
     NOCACHE;

 -- 테이블 생성
 CREATE TABLE TB_BOARD (
                           IDX NUMBER NOT NULL,
                           CONTENTS VARCHAR2(255),
                           CREATED_AT TIMESTAMP,
                           CREATED_BY VARCHAR2(255),
                           TITLE VARCHAR2(255),
                           CONSTRAINT PK_TB_BOARD PRIMARY KEY (IDX)
 );

 -- 트리거 생성
 CREATE OR REPLACE TRIGGER TRG_TB_BOARD
     BEFORE INSERT ON TB_BOARD
     FOR EACH ROW
 BEGIN
     :NEW.IDX := SEQ_TB_BOARD.NEXTVAL;
 END;

